### ISSUE TITLE
Please add F3 at the 5 percentage points

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/FAVE#1]
from Jim's comment on the darlaweb repo:

Would it be possible to add F3@20%, F3@35%, F3@50%, F3@65%, F3@80%? DARLA already provides these values for F1 and F2, but not F3.  We need it for rhoticity.  Thanks!

**Comment by michaellefkowitz** [comment]
Got it, this will be the first priority after getting the code to run as is.

**Comment by sravanareddy** [comment]
Jim, how soon do you want this integrated into Darla?

**Comment by JimStanford99** [comment]
This is an outdated issue since Michael has now added F3 for every 10% interval in the FAVE code, which is better than the original request (15%). Is there more work that needs to be done to implement it in DARLA?

**Comment by sravanareddy** [comment]
Yes, I'll need to move it to the server, and put in some of our changes, like the normalized formants. That part's ok, but it will take me some time to integrate the phonetic environment probabilities back into it. For now, I could ignore the probabilities and just put this code in so you guys can start working on rhoticity?

**Comment by JimStanford99** [comment]
Yes, all good. But there's no rush of F3. We'd rather that you put your
time resources into Kaldi.
