### ISSUE TITLE
Column headers in output file

### ISSUE THREAD

**Issue by sravanareddy** [sravanareddy/FAVE#2]
(from Jim's comment in darlaweb repo)

Please change the following headers in the output file:
plt_manner = fol_manner
plt_manner_prob = fol_manner_prob
plt_place = fol_place
plt_place_prob = fol_place_prob
plt_voice = fol_voice
plt_voice = fol_voice_prob
plt_preseq = preseq
plt_folseq= folseq

**Comment by sravanareddy** [comment]
Made the change in the repo code.

**Comment by JimStanford99** [comment]
Thanks!

**Comment by sravanareddy** [comment]
Note that the change is still not in Darla -- we won't incorporate the FAVE
changes immediately.
