### ISSUE TITLE
Upload simple boundaries TextGrids

### ISSUE THREAD

**Issue by JimStanford99** [sravanareddy/FAVE#5]
For day-to-day use of DARLA as a FAVE interface, it would be very helpful to have an option to directly upload a TextGrid with boundaries that the user has annotated in Praat as TextGrids, i.e., boundaries paired around a sentence or two at a time). This is the same technology as FAVE, of course, but it would save two steps for users. With the online FAVE interface, users have to first run a Praat script, then upload to FAVE-Align, then get the output via email, then upload it to FAVE-Extract, then finally get the final output via email. This is okay if a person is only running a few files, but for large long-term projects, it is more difficult. An easier method via DARLA would be to directly upload the TextGrid with boundaries and then send back the final results. This would be especially good for users without computer background (running Praat scripts and keeping track of multiple outputs via email). Also, it would enable the data to run through DARLA's output format, which includes instant plots and other useful features.

**Comment by sravanareddy** [comment]
Requires working with FAVE-align. Change input format to the main alignment script.

**Comment by sravanareddy** [comment]
Just remembered that we switched to ProsodyLab aligner, so this should be incorporated into our code, not FAVE align as I said earlier.

**Comment by JimStanford99** [comment]
Oh, good. So a little easier to do?

**Comment by sravanareddy** [comment]
Yes, a lot easier.

**Comment by sravanareddy** [comment]
Taking the lead on this since it's not really FAVE.

**Comment by sravanareddy** [comment]
Can you put a sample TextGrid-with-boundaries file in a Dropbox folder, in the format that we want users to upload?

**Comment by JimStanford99** [comment]
Here is a sample TextGrid and WAV file:
https://www.dropbox.com/sh/7gpoxbvcgsm159a/AACwOhZdkcUO8fANc7qKZXPva?dl=0

**Comment by sravanareddy** [comment]
Ready to test on the dev site. It works on the sample.

**Comment by sravanareddy** [comment]
Merges TextGrids now.

**Comment by sravanareddy** [comment]
Boundaries offset seems to be corrected; please test.

**Comment by JimStanford99** [comment]
Thanks, it's better but it still gets off-track at the end of the
recording. Please see the last sentence.
The aligned TextGrid that I just received from DARLA is
LC_Madison_Bud8-11-2015.TextGrid

**Comment by JimStanford99** [comment]
The FAVE-Align version doesn't have this problem. See "FAVE-AlignLC_Madison_PBud.TextGrid", which is the TextGrid output that I just got using the regular FAVE-Align online tool. Note the correct alignment in the sentence at the end of the recording, unlike ours. Sorry.

**Comment by JimStanford99** [comment]
When I ran the same thing through FAVE-Align (via the Praat script, etc.),
it aligns correctly, even at the end of the recording. Sorry.

**Comment by sravanareddy** [comment]
Ok. Basically, the issue is that ProsodyLab aligner is trimming silences at the ends, so I have to correct for that when they're concatenated together. I'll fix it by today.

**Comment by sravanareddy** [comment]
Try again?

**Comment by JimStanford99** [comment]
Can you please resend me the website for boundaries? I don't have it on
this laptop.

**Comment by sravanareddy** [comment]
http://darla.dartmouth.edu:8080/main.py/uploadtrans

**Comment by JimStanford99** [comment]
"Unfortunately, there was an error trying to start a file for LC_Madison_Bud_copy. We could not just_align_extract shell script"

**Comment by sravanareddy** [comment]
Hope it works now!

**Comment by sravanareddy** [comment]
This issue was moved to sravanareddy/darlaweb#47
